project_id = "ybapyboqofmqufzvkyov"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant = "realtime"
max_concurrent_users = 200

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
inactivity_timeout = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false
password_min_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
test_otp = "123456"

[edge_functions]
enabled = true
port = 54328
inspector_port = 5555

[functions.wellness-chat]
verify_jwt = false

[email.testing]
enabled = true
port = 54329
vector_port = 54330
policy_port = 54331
tenant_id = "stub_tenant"
region = "stub_region"
volume_id = "stub_volume"
webhook_secret = "v1,whsec_stub"
anon_key = "stub_anon_key"